### ISSUE TITLE
Fix 'The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3.' issue in Python\rsa_api_full_example.py

### ISSUE THREAD

**Issue by zkoppert** [TekRTSA/RSA_API#12]
[CodeFactor](https://www.codefactor.io/repository/github/tektronix/rsa_api) found an issue: The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3.

It's currently on:
[Python\rsa_api_full_example.py:79
](https://www.codefactor.io/repository/github/tektronix/rsa_api/source/master/Python/rsa_api_full_example.py#L79)

**Comment by ghost** [comment]
A good explanation of the issue:
https://www.geeksforgeeks.org/vulnerability-input-function-python-2-x/

**Comment by ghost** [comment]
Some error handling will be necessary as well in the event `raw_input` is used but the user decides to provide a non-integer value that we try to cast as an `int`

**Comment by ghost** [comment]
#13 closes this I believe.
